version: "3.9"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  backend:
#    build: ./
#    container_name: backend
#    ports:
#      - "5000:5000"
#    depends_on:
#      - postgres
#    environment:
#      - SERVER_PORT = 5000
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/database

  frontend:
#    depends_on:
#      - backend
    container_name: frontend
    build: D:\Projects\business-project-frontend
    restart: always
    ports:
      - "3000:80"
volumes:
  db-data:
