package ru.spbu.project.models.enums;

public enum Stage {

  WAITING_APPLICATION_TRAINING,
  REFUSAL_APPLICATION,
  PASSES_ENTRANCE_TEST,
  FAILED_ENTRANCE_TEST,
  STUDYING,
  FAILED_STUDYING,
  EXPECTS_PRODUCTION_PRACTICE,
  PRODUCTION_PRACTICE,
  FAILED_PRODUCTION_PRACTICE,
  EXAM,
  GRADUATED,
  PASSED_EXAM,
  FAILED_EXAM,
}
